name: M3U generator

on:
  schedule:
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main
      - global

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Run script
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: Git add
        run: |
          git add -A
          ls -la

      - name: Commit & Push changes
        run: |
          git commit -m "Links are updated by robot 🤖"
          git push

      # Add this step for Telegram notification
      - name: Notify via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "M3U files updated successfully! 🚀  \`https://raw.githubusercontent.com/Nuttypro69/YouTube_to_m3u/main/youtube.m3u\` "
